# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - eduardoteste

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
  # PYTHON_VERSION: '3.13' # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
    # permissions:
      id-token: write #This is required for requesting the JWT
      # contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Setup Python version
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: ${{ env.PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      # - name: Create and start virtual environment
      #   run: |
      #     python -m venv venv
      #     source venv/bin/activate

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      # Optional: Add step to run tests here

      # - name: Zip artifact for deployment
      #   run: zip release.zip ./* -r

      - name: Create .python_packages folder
        run: mkdir -p .python_packages/lib 

      - name: Install the project dependencies
        run: uv sync --locked --all-extras --dev

      - name: Copy the project dependencies to the .python_packages folder
        run: cp -r .venv/lib/python3.13/site-packages .python_packages/lib/

      - name: Remove uv auto-generated files
        run: rm .python_packages/lib/site-packages/_virtualenv.*

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1DF0F1213CA34E6FBE14FF7AD03A8E9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_826A08197C6F4949B7DD33F4F0285428 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_31D8520F3B8B4B4099569291A47DC2EB }}

      - name: 'Deploy to Azure Functions'
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'eduardoteste'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: python-app
      #     path: |
      #       release.zip
      #       !venv/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   permissions:
  #     id-token: write #This is required for requesting the JWT
  #     contents: read #This is required for actions/checkout

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: python-app

  #     - name: Unzip artifact for deployment
  #       run: |
  #         unzip release.zip
  #         rm release.zip
        
  #     - name: Login to Azure
  #       uses: azure/login@v2
  #       with:
  #         client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1DF0F1213CA34E6FBE14FF7AD03A8E9C }}
  #         tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_826A08197C6F4949B7DD33F4F0285428 }}
  #         subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_31D8520F3B8B4B4099569291A47DC2EB }}

  #     - name: 'Deploy to Azure Functions'
  #       uses: Azure/functions-action@v1
  #       id: deploy-to-function
  #       with:
  #         app-name: 'eduardoteste'
  #         slot-name: 'Production'
  #         package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          